include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated/**"
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    dead_code: error
    unused_import: error
    unused_local_variable: warning
    unused_element: warning
    unreachable_from_main: warning
    avoid_print: warning

linter:
  rules:
    - always_declare_return_types
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_final_locals
    - directives_ordering
    - sort_pub_dependencies
    - use_key_in_widget_constructors
    - constant_identifier_names
    - avoid_redundant_argument_values
dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    lines-of-code: 120
    number-of-parameters: 5
    maximum-nesting-level: 5
  metrics-exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  rules:
    - no-boolean-literal-compare
    - no-equal-then-else
    - prefer-single-widget-per-file
    - prefer-match-file-name
  anti-patterns:
    - long-method
