name: money_tracker
description: "Finoro - A modern personal finance app that helps you organize, track, and understand your money through Projects."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cloud_firestore: ^6.0.3
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  firebase_auth: ^6.1.1
  firebase_core: ^4.2.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  freezed_annotation: ^3.1.0
  go_router: ^16.2.5
  google_sign_in: ^6.2.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  package_info_plus: ^8.0.0
  shared_preferences: ^2.5.3
  sign_in_with_apple: ^7.0.1
  url_launcher: ^6.3.1
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.5.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.1.0
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icon/app_icon.png

flutter_launcher_icons:
  android: false
  ios: true
  image_path: "assets/icon/app_icon.png"
  remove_alpha_ios: true

localizations:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
