// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkg5_Cuvd_wA6QUUJ_f5nSRm1MkKc58jo',
    appId: '1:895348126223:ios:813663ecac8ee2faac697a',
    messagingSenderId: '895348126223',
    projectId: 'moneytracker-5c1e6',
    storageBucket: 'moneytracker-5c1e6.firebasestorage.app',
    iosBundleId: 'com.korotindenys.moneyTracker',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH6z3IrbTY7-fOCsvRtQzOjdjYcde81gk',
    appId: '1:895348126223:android:7b74c82f6cdfa628ac697a',
    messagingSenderId: '895348126223',
    projectId: 'moneytracker-5c1e6',
    storageBucket: 'moneytracker-5c1e6.firebasestorage.app',
  );

}